import 'bootstrap/dist/css/bootstrap.css';
import '../sass/globals.scss';
import { Lato } from 'next/font/google';
import { GlobalsContext } from '@/context/globalContext';

const lato = Lato({
  subsets: ['latin'],
  weight: ['100', '300', '400', '700', '900'],
});

export const metadata = {
  title: 'PokeApp',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <GlobalsContext>{children}</GlobalsContext>
      </body>
    </html>
  );
}
